spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Control_DB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
#        temp:
#          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:liquibase/changelog.yml