spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Control_DB
    user: postgres
    psw: postgres
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  hibernate:
    ddl-auto=none
  liquibase:
    change-log: classpath:liquibase/changelog.yml